### PR TITLE
Responsive my donations table. Closes #607.

### LINKED ISSUE #607: Responsive Layout for My Donations table
Here's a screenshot of the My Recurring Donations Table on mobile devices:
image

It's pretty similar to the My Donations table. I think we could do better about make tables more responsive. Perhaps with something like the following: https://codepen.io/anon/pen/zLxLwE which uses data-attributes and CSS `::before` pseudo selectors.

### PR DESCRIPTION
**Pull request by helgatheviking**
Result will be slightly theme dependent....

Here's the Beaver Builder theme:
table reading My Donations, showing test donations in Beaver Builder Theme

Here's Divi (which I find a bit harder to read due to lack of striping)
table reading My Donations, showing test donations in Divi theme

Here's Twenty Seventeen (with some weird indents)
table reading My Donations, showing test donations in TwentySeventeen theme

### CODE REVIEW

**Comment by ericnicolaas** [comment]
Looking pretty 👍 to me! 

@wesfranklin What do you think?

**Comment by wesfranklin** [comment]
On that Divi one (and others that are styled similarly) can there be a thicker line between sections to make it easier to see where one starts and ends?

**Comment by helgatheviking** [comment]
I didn't add any borders at all as I allowed the theme's table styles to take control. Do you want to mock something up specific to Charitable?

**Comment by wesfranklin** [comment]
@helgatheviking In that case, but it's fine to leave it as is.

**Comment by helgatheviking** [comment]
Cool! Should we do something about Twenty Seventeens weird indents? Or same, leave the theme to do it's thing?

**Comment by wesfranklin** [comment]
@helgatheviking They are weird, but not too bad. Maybe they're ok as is.

**Comment by ericnicolaas** [comment]
@helgatheviking @wesfranklin:

I've been playing around with this a bit today. If we slap in a lot of `!important` tags we can be forceful enough to override some of the weird theme quirks. I know it's not ideal, but I wonder if it might be worth doing as a way to provide some sensible defaults at least.

**Divi**
Screenshot 2019-05-27 13 21 52

**Twentynineteen**
Screenshot 2019-05-27 13 23 10

**Twentyseventeen**
Screenshot 2019-05-27 13 27 20

Here's the CSS I've added (on top of what you already had Kathy):

```
.charitable-table {
    border: none !important;
}

.charitable-table tr {
    margin-bottom: 1em;
}

.charitable-table tr td {
    padding: 0.5em 0 !important;
    border: none !important;
}
```

**Comment by helgatheviking** [comment]
I kinda like it. Is this only for the mobile view? Or all charitable tables?

**Comment by wesfranklin** [comment]
@ericnicolaas Yep, that's good!

**Pull request merged**
