### PR TITLE
add debug log option to PayPal. closes #229.

### LINKED ISSUE #229: Add debug option for paypal
Add an option to log the paypal IPN notifications (the easiest would be to just use `error_log()` and require that `WP_DEBUG_LOG` is enabled).

to get really advanced, we could create our own file with appropriate .htaccess security and delete it when not in debug mode, but this was quick and not too dirty.

### PR DESCRIPTION
**Pull request by helgatheviking**
add setting and if setting is true, log json-encoded `$data` to `WP_DEBUG_LOG`

### CODE REVIEW

**Comment by ericnicolaas** [comment]
@helgatheviking I'm not convinced about adding this as a setting; would prefer to use a filter since this is really a developer-oriented feature.

**Comment by helgatheviking** [comment]
maybe 

```
if ( $gateway->get_value( 'debug_log' ) ) {
	error_log( json_encode( $data ) );
}
```

could be 

```
if ( defined('CHARITABLE_DEBUG') && CHARITABLE_DEBUG ) ) {
	error_log( json_encode( $data ) );
}
```

**Comment by ericnicolaas** [comment]
Yep, happy with that.

**Comment by ericnicolaas** [comment]
This was merged in through #237.

**Pull request closed without merging**
