### PR TITLE
Add basic styling for the [charitable_my_donations] table

### PR DESCRIPTION
**Pull request by helgatheviking**
Happy #Hacktoberfest!

Here's a starting point for some table styling:

Desktop view:

desktop view of my donations table

Mobile view:
mobile view of my donations table

### CODE REVIEW

**Comment by ericnicolaas** [comment]
Oooh, that's looking pretty tidy! @wesfranklin thoughts?

**Comment by wesfranklin** [comment]
Yep, looks great

**Comment by helgatheviking** [comment]
when this gets merged in, I want to get the recurring tables to match.

**Comment by ericnicolaas** [comment]
Just trialing this with a bunch of different themes. For the most part it's fine across the board, but I think the borders are a bit of an issue. I think it would probably be best to not apply any border styles at all — this way, the theme's default table styles will apply instead.

### Divi

Screenshot 2020-07-07 11 56 37

### Astra

Screenshot 2020-07-07 11 52 19

### Born to Give

Screenshot 2020-07-07 11 52 37

### Charity Home

Screenshot 2020-07-07 11 53 33

### Hello Elementor

Screenshot 2020-07-07 11 54 07

### GeneratePress

Screenshot 2020-07-07 11 54 30

**Comment by ericnicolaas** [comment]
Looking at this in mobile view, one issue is that with the Gift Aid extension, we add a column. However, the cell can be blank if Gift Aid wasn't claimed on a donation.

It's missing the data-title attribute at the moment, but even if I add that, when the donation has no Gift Aid, it results in awkward margins:

Screenshot 2020-07-07 12 09 33
Screenshot 2020-07-07 12 09 24

I think we could avoid this as a problem by removing the float on the label:

Screenshot 2020-07-07 12 10 15
Screenshot 2020-07-07 12 10 20

**Comment by ericnicolaas** [comment]
I have merged this with some changes. Adding some screenshots here. 

### Divi

Screenshot 2020-07-07 12 22 09
Screenshot 2020-07-07 12 24 44

### Astra

Screenshot 2020-07-07 12 25 12
Screenshot 2020-07-07 12 25 23

### Hello Elementor

Screenshot 2020-07-07 12 27 32
Screenshot 2020-07-07 12 27 41

Little bit awkward there with the mobile view. 

### GeneratePress

Screenshot 2020-07-07 12 28 32
Screenshot 2020-07-07 12 28 40

### Born to Give

Screenshot 2020-07-07 12 29 09
Screenshot 2020-07-07 12 29 16

### Charity Home

Screenshot 2020-07-07 12 29 40
Screenshot 2020-07-07 12 29 49

**Comment by ericnicolaas** [comment]
The only thing I'm not sure about is the right align of the "View Receipt" link in mobile. We could get rid of that, in which case it will sit wherever the rest of the text is or in the middle (with Charity Home).

@wesfranklin Your thoughts on how this is looking?

**Comment by wesfranklin** [comment]
@ericnicolaas Yeah, the right align does feel awkward. I think it'd be fine if it was aligned in the same way as the other rows.

**Pull request merged**
