### PR TITLE
Feature/paypal api settings

### PR DESCRIPTION
**Pull request by helgatheviking**
gonna need these for cancelling subs

### CODE REVIEW

**Comment by helgatheviking** [comment]
@ericnicolaas any thoughts on getting this merged in soon?

**Comment by ericnicolaas** [comment]
@helgatheviking This is looking good; I'm going to aim for merge this week. Aiming for a 1.6 release this month.

**Comment by helgatheviking** [comment]
That sounds great! I'm aiming for 1.1 this month too.

**Comment by ericnicolaas** [comment]
I think the copy on the settings page needs to include a more detailed explanation of how to obtain API keys. We can create some documentation on our site similar to what EDD have (https://docs.easydigitaldownloads.com/article/1330-how-to-get-paypal-api-keys) but just a link with quick instructions on how to get the API keys will be good. 

@helgatheviking Can you confirm: Is "NVP/SOAP API integration (Classic)" the one we need people to use? 

screenshot 2018-04-10 11 54 44

**Comment by ericnicolaas** [comment]
@helgatheviking FYI I have merged this into `release/1.6.0` so I will close the PR.

**Comment by helgatheviking** [comment]
Ok, I'll take a look. I thought I had a direct link. And I still haven't written the PayPal part yet, but pretty sure those are the right API credentials based on how EDD is doing it.

**Comment by ericnicolaas** [comment]
I've left this open, but planning to merge `release/1.6.0` into `master` today to provide better clarity about what's done and isn't done. 

You do have a direct link, but at least when I used it in test mode, it just landed me in the PayPal account dashboard. The link is https://www.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run. 

With the new PayPal account area, the link for obtaining the live keys is https://www.paypal.com/businessmanage/credentials/apiAccess

For Sandbox, it looks like you have to go to developer.paypal.com, then go to Your Accounts, find the Seller account you're using, click on Profile and then click on the API keys tab — so a bit more complicated!

**Comment by ericnicolaas** [comment]
Also, I think we need to have links to both all the time, regardless of whether the user is in test mode or not. Otherwise they'll just assume they can get both the sandbox & live API credentials through the one link.

**Comment by helgatheviking** [comment]
yeah, you need both, but PayPal is a PITA and doesn't make it easy to get both at the same time.

**Comment by ericnicolaas** [comment]
Merged into `master`.

**Pull request closed without merging**
