### PR TITLE
Sortable amounts

### PR DESCRIPTION
**Pull request by helgatheviking**
If you get the order of amounts wrong, you have to redo all the amounts in the right order. So instead, I propose adding delete and sort functions.

image

Additionally, I've changed the way that the rows are cloned so that the JS will automatically take into account any new `$fields`. I'm cloning a hidden row instead of hard-coding the row in javascript.

### CODE REVIEW

**Comment by ericnicolaas** [comment]
I am definitely in favour of making the rows sortable and able to be deleted, but not 100% sure about the UI. Looping in @wesfranklin for his opinion.

**Comment by helgatheviking** [comment]
Anything particular about the UI that bugs you? Would it be better to move the "re-order" over on the right next to the remove column.

**Comment by ericnicolaas** [comment]
Yeah, I think that would help. I'm also not sure about the up/down icons.

**Comment by helgatheviking** [comment]
Ok, I can do that. I don't love the arrows. I wanted something similar to a "move" cursor, but there doesn't seem to be one in the dashicons icon set.

**Comment by wesfranklin** [comment]
Yeah, Dashicons don't have a good icon for reordering. We might need to create a custom icon. 2 rows on dots are often used for reordering, I think Gmail uses that.

I'm ok with the reorder icons on the left. How does the reotdering work? Is it drag and drop?

I think the remove icons don't need to be red, they stand out too much at the moment.

**Comment by wesfranklin** [comment]
Here is a screenshot from Asana of the 'grippy dots' indicating an item that can be reordered.

screen shot 2016-01-13 at 10 35 19 am

**Comment by helgatheviking** [comment]
Ditching the red is easy and I will see what I can do about the column widths. I didn't really do anything about so this is just default. 

WooCommerce is using the hamburger menu for re-ordering:
image

probably in an effort to use something from dashicons. But I like the grippy dots! The question then is it worth adding an icon font to charitable just for this one icon.

**Comment by wesfranklin** [comment]
The hamburger icon may work, though it's a little confusing because it is normally used for menus. There is a version of the hamburger icon with four lines instead of three, maybe this would be better?

**Comment by helgatheviking** [comment]
I agree. I think it was just a desperation thing since there isn't really a good dashicon. Here's a [cheat sheet](http://calebserna.com/dashicons-cheatsheet/). WooCommerce created their own icon font, so I'm surprised they didn't do something better there. Here though, I don't think you have a special font already so I'm not sure it is worth the weight/effort.

**Comment by ericnicolaas** [comment]
No problems adding a custom icon; we already load an icon font in Charitable for the menu icons. Something like Asana's would be nice.

**Comment by helgatheviking** [comment]
Didn't notice you had a font yet. Still digging in! What about one of the suggestions found [here](https://github.com/FortAwesome/Font-Awesome/issues/816)... specifically this [svg](https://dl.dropboxusercontent.com/u/3892745/icon/grab.svg)?

**Comment by ericnicolaas** [comment]
Yeah, lots of stuff hidden away in Charitable that we haven't really documented very well. :)

I'm not opposed to that icon. @wesfranklin? 

FYI: I created the icon set through IcoMoon, so the absolute easiest is to pick an icon from there. Or if Wes puts together the icon I can load it into the existing font.

**Comment by helgatheviking** [comment]
You can also create a custom font with https://icomoon.io/app/. You can start by uploading your existing font and then the new icon. I'd do it, but it's a little late here now, so I will leave that to you gents. I should be able to address the rest of this tomorrow.

**Comment by wesfranklin** [comment]
Let's use that SVG in a light grey - can you load it Eric?
Github isn't allowing me to upload it here.

**Comment by helgatheviking** [comment]
UI tweaks: 
image

**Comment by wesfranklin** [comment]
Looks pretty good to me.

**Comment by ericnicolaas** [comment]
Found an incompatibility bug with the Layers theme by Obox: 

screenshot 2016-01-08 10 43 00

This is going to be the same with any other theme/plugin that happens to have loaded a custom icon font. To get around it, I suggest _removing_ the `font-family` setting from the `[class^="icon-"], [class*=" icon-"]` selector and instead adding that to each individual icon selector: 
````
[class^="icon-"], [class*=" icon-"] {
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;

	/* Better Font Rendering =========== */
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}

.icon-donations:before {
	font-family: 'charitable';
	content: "\e600";
}

.icon-charitable:before {
	font-family: 'charitable';
	content: "\e601";
}

.icon-campaign-creator:before {
	font-family: 'charitable';
	content: "\e602";
}

.icon-donations-grab:before {
	font-family: 'charitable';
	content: "\e603";
}
````
The second issue here is that the icon is too big because of Layers, so an explicit font-size needs to be set. I'm proposing `20px`, which matches the remove icon. 

And finally - and I know this is me being a giant pain - after the change of icon I think it works better to have it on the left. I'd also suggest removing the column headers to clean up the UI a little; I think the icons speak for themselves. 

screenshot 2016-01-08 10 43 00

@helgatheviking, I just set up a `feature/sortable-amounts` branch. Could you make the pull request against that branch? Then if you and @wesfranklin are happy with my changes, I can merge those in before merging back into `master`?

**Comment by ericnicolaas** [comment]
Merged in 7ff291e0bccabdd16d7770653982102f3384e40f

**Pull request closed without merging**
