### PR TITLE
Use default edit.php?post_type=donation. closes #110.

### LINKED ISSUE #110: Use default edit.php?post_type=donation
Instead of the custom `admin.php?page=charitable-donations-table` page, I think you can use the core `edit.php?post_type=donation` page with a few tweaks. with a little bit of style it's not far off and if I really tried I might be able to get the exact same look as currently in Charitable without needing custom `admin.php` pages. 

image

### PR DESCRIPTION
**Pull request by helgatheviking**
I've got ordering by the amount column in here, but I'm a little iffy on the SQL for that b/c what i have doesn't take into account the possibility of donating to multiple campaigns on the same donation. I think you'd need a `SUM()` statement.

### CODE REVIEW

**Comment by ericnicolaas** [comment]
This is coming along ok, but there are a few things that are missing or not quite right. 

- Bulk Actions is gone. Definitely need to keep that :)
- Pagination can go below the filters box, on the same line as the Bulk Actions. This is consistent with other post tables. It will also avoid a issue when viewing the page at certain sizes (screenshot below): screenshot 2016-05-30 13 02 29

I'm really happy with moving the Search above the filter box, and the addition of the Clear Filter button. Also like the idea of using some colour for the donation status, though I'll get @wesfranklin to look at that from a design perspective. 

screenshot 2016-05-30 13 10 52

**Comment by ericnicolaas** [comment]
@helgatheviking To allow us to collaborate on this one, I have created a new branch: https://github.com/Charitable/Charitable/tree/pr/132 

I made a couple small changes already to prefer the use of `charitable_format_money()`, which is basically a shorthand way of doing `charitable_get_currency_helper()->get_monetary_amount()`.

**Comment by helgatheviking** [comment]
Oops, i don't even remember the bulk actions being there. the trouble there is going to be that WordPress core has a five year old [trac ticket](https://core.trac.wordpress.org/ticket/160310) related to *adding* bulk actions. But there are some hacky methods until that makes core.... if ever. 

The bulk actions are actually on the same line as the pagination:
posts

Clear button doesn't actually exist anywhere else, but it makes sense to me, even though it kind of gets in the way of the export button. I'd probably vote to undo the border and background color so that it matches the default. what do you think?

image

**Comment by ericnicolaas** [comment]
Yes to having bulk actions on the same line as pagination. I'm not sure why the bulk actions aren't there by default actually. 

Not keen on getting rid of the border & background. I know we're adding something that isn't the default, but with all those extra filters & actions, it's useful to have the visual separation.

**Comment by helgatheviking** [comment]
>Yes to having bulk actions on the same line as pagination. I'm not sure why the bulk actions aren't there by default actually.

At wide screen widths everything ends up on the same line

image

but as the screen narrows the various items begin to wrap. 

Once you start including the pagination (and you almost have to since ) I don't know that the extra border/background really adds that much. For example, here's shop orders which has few extra filters but no special styling:
image

Because of where the `div` elements wrap it's pretty much impossible to get the exact same look you had before, but to me, it's a small sacrifice to get back to default looks/functionality. 

You could do this (either way I think I like narrowing the date inputs):

image

**Comment by wesfranklin** [comment]
@ericnicolaas @helgatheviking in terms of using colour for the donation status - I like it, but maybe it could be simplified by removing the border on each and the text shadow?

I think 'Refunded' could be a blue, then 'Pending' could be grey, and 'Failed' could be orange - thoughts?

For the Donations UI - doesn't the pagination normally go below the list of donations?

**Comment by helgatheviking** [comment]
@wesfranklin Normally the pagination goes above *and* below the posts table. That color coding sounds okay to me. Got any preferred hex codes?

I'd prefer a way to get everything all on one line like so:

image

but once you have bulk actions, beginning & end dates, and a filter button that becomes a lot.

**Comment by wesfranklin** [comment]
@helgatheviking 'Refunded' could be something like #3fb8f5 and 'Failed' could be #f7a129

**Comment by ericnicolaas** [comment]
I'm closing this PR in favour of the work in https://github.com/Charitable/Charitable/tree/issue/110b.

**Pull request closed without merging**
