### PR TITLE
Implementing flexbox to make sure columns always stay equal height

### LINKED ISSUE #315: On mobile, campaign summary layout breaks
screenshot 2017-03-20 11 00 04

### PR DESCRIPTION
**Pull request by kkoppenhaver**
Fixes #315 

Using flexbox to achieve this makes sure the columns are always equal height. I've tested on all widths down to below 300px and the layout still doesn't break as show in the screenshot.

The only downside to this approach is that legacy IE support isn't great. Depending on which versions of IE you're looking to support we might need to take a different tack.

What are your standards for browser support?

### CODE REVIEW

**Comment by ericnicolaas** [comment]
@kkoppenhaver Thanks for the contribution!

Since Charitable is used by a very wide range of sites, we generally aim for broad browser coverage. That said, what would be the impact of your PR for IE 10 and below? Does it just mean they will be stuck with the status quo? i.e. It doesn't have any effect on them?

**Comment by kkoppenhaver** [comment]
Just tested on my IE virtual machines and it looks like the bug still exists as documented in IE 9 and IE 10. So, you're correct, no effect.

**Comment by ericnicolaas** [comment]
@kkoppenhaver That sounds great. If there's a CSS-only option that will work more broadly, that would be ideal; otherwise I'm happy with something that improves the situation for 97% of users without making things worse for the few who are still hacking their way around on old browsers.

**Comment by kkoppenhaver** [comment]
All I've been able to find on this is JS polyfills, which I'm assuming we don't want to add.

I think for now, dropping in flexbox and fixing it for the majority of clients is the best approach.

**Pull request merged**
