### PR TITLE
Add donation_gateway as optinal field for donation export

### PR DESCRIPTION
**Pull request by rafecolton**
I would love to include the proper donation gateway name (i.e. `Authorize.Net` instead of `authorize_net`), but I don't see a clean way to do this with just a db query, since the value is stored in code

### CODE REVIEW

**Comment by ericnicolaas** [comment]
@rafecolton Is the purpose of this to add the gateway to the export CSV as a new column? Or is it to allow donations to be filtered by gateway before they are exported (i.e. only download PayPal donations)? Or both?

**Comment by rafecolton** [comment]
The former. Our accounting team needs to know the payment gateway for separating revenue streams, and they need to know which donations are offline so they can associate the check or cash that was used for payment.

**Comment by rafecolton** [comment]
For context, I used this in conjunction with this filter:

```php
function ch_add_donation_export_columns( $columns, $report_args ) {
  $columns[ 'donation_gateway' ] = 'Donation Gateway';
  return $columns;
}

add_filter( 'charitable_export_donations_columns', 'ch_add_donation_export_columns', 10, 2 );
```

**Comment by rafecolton** [comment]
Closing in favor of https://github.com/Charitable/Charitable/pull/177

**Pull request closed without merging**
